export const packagePages = {
  "/": {
    "route": "/",
    "name": "Home Page",
    "title": "Hard Inquiry Removal | 100,437 Removed | Inquiry Removal",
    "description": "Remove unauthorized hard inquiries from your credit report — all 3 bureaus. 100,437+ removed since 2015. Free consult. Flat fee. Get started today.",
    "h1": "Hard Inquiry Removal — Stop Unauthorized Pulls. Reclaim Your Score.",
    "lede": "We remove hard inquiries from your Experian, Equifax, and TransUnion credit reports — using federal law, custom disputes, and 11 years of specialized experience — so your score goes back up and you finally get approved for what matters most.",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Get My Free Credit Analysis",
    "secondaryCta": "See How It Works",
    "secondaryHref": "/how-it-works"
  },
  "/services": {
    "route": "/services",
    "name": "Services Page",
    "title": "Hard Inquiry Removal Plans | Flat Fee | Inquiry Removal",
    "description": "Remove hard inquiries — 1 or 100. Flat-fee plans from $199, built for your situation. Free consultation. Custom disputes. All 3 bureaus. Guarantee.",
    "h1": "Hard Inquiry Removal Plans — Flat Fee, Built for Your Inquiry Count",
    "lede": "Every credit report is different. Every situation is different. That's why we built three flat-fee plans based on your total inquiry count — so you only pay for what you actually need, and you get the same white-glove service regardless of which tier you're in.",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Get My Free Credit Analysis",
    "secondaryCta": "Call Us Directly — 602-377-6626",
    "secondaryHref": "tel:+16023776626"
  },
  "/about": {
    "route": "/about",
    "name": "About Page",
    "title": "About | Hard Inquiry Specialist Since 2015 | Inquiry Removal",
    "description": "Robert Garcia built Inquiry Removal after unauthorized hard inquiries wrecked his perfect credit. Learn why that experience changes everything.",
    "h1": "Hard Inquiry Removal — Who We Are and Why We Built This",
    "lede": "Not a company that charges you every month while your score stands still. Not a call center that transfers you three times before anyone picks up. Someone who has lived this problem, spent a career learning the law behind it, and built an entire company around solving it — and nothing else.",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Book My Free Consultation",
    "secondaryCta": "See How It Works →",
    "secondaryHref": "/how-it-works"
  },
  "/how-it-works": {
    "route": "/how-it-works",
    "name": "How It Works Page",
    "title": "Hard Inquiry Removal: How It Works | Inquiry Removal",
    "description": "See exactly how our hard inquiry removal process works — step by step, real timelines, zero surprises. Free consultation to start.",
    "h1": "Hard Inquiry Removal: Simple Steps, Real Results, Zero Surprises",
    "lede": "Most people who come to us have never done this before. They don't know what to expect, they've heard conflicting things about what's possible, and the last thing they need is a process that adds more confusion to an already frustrating situation. So here is every step — in plain language, with real timeframes — so you know exactly what you're walking into before you spend a single dollar.",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Book My Free Consultation",
    "secondaryCta": "See Our Results →",
    "secondaryHref": "/results"
  },
  "/results": {
    "route": "/results",
    "name": "Results Page",
    "title": "Hard Inquiry Removal Results | Real Proof | Inquiry Removal",
    "description": "Hard inquiry removal results — real clients, real proof. 100,437 inquiries deleted. Scores up 50–100+ points. See case studies and testimonials.",
    "h1": "Hard Inquiry Removal Results — 100,437 Removed. Here's the Proof.",
    "lede": "Numbers are easy to say. What they mean for an actual person — a home they finally qualified for, a car loan at a rate that made sense, a credit report that finally reflects who they actually are — that is what this page is about.",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Get My Free Credit Analysis",
    "secondaryCta": "See How It Works →",
    "secondaryHref": "/how-it-works"
  },
  "/pricing": {
    "route": "/pricing",
    "name": "Pricing Page",
    "title": "Hard Inquiry Removal Pricing | From $199 | Inquiry Removal",
    "description": "Hard inquiry removal plans from $199 — one flat fee, no monthly charges. Plans sized by inquiry count. Free consultation. 100% money-back guarantee.",
    "h1": "Hard Inquiry Removal Pricing — One Flat Fee. No Monthly Charges.",
    "lede": "The price of removing hard inquiries is a flat fee between $199 and $499. The price of leaving them there is measured in interest rates, loan denials, and the financial opportunities that quietly disappear while your score stays suppressed.",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Book My Free Consultation",
    "secondaryCta": "See How It Works",
    "secondaryHref": "/how-it-works"
  },
  "/comparison": {
    "route": "/comparison",
    "name": "Comparison Page",
    "title": "Inquiry Removal vs Lexington Law, Credit Saint & Credit People",
    "description": "Comparing credit repair services for hard inquiry removal? Honest side-by-side: Inquiry Removal vs Lexington Law, Credit Saint, and Credit People.",
    "h1": "Hard Inquiry Removal vs Subscription Services — An Honest Comparison",
    "lede": "If you're weighing Inquiry Removal against Lexington Law, Credit Saint, or The Credit People, this page gives you the side-by-side you actually need — with no spin, no cherry-picked stats, and no pretending we're the right fit for every situation. Because we're not. And knowing the difference is what helps you make the right call.",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Book My Free Consultation",
    "secondaryCta": "See How It Works",
    "secondaryHref": "/how-it-works"
  },
  "/get-started": {
    "route": "/get-started",
    "name": "Get Started Page",
    "title": "Hard Inquiry Removal Consultation | Free | Inquiry Removal",
    "description": "Book your free hard inquiry removal consultation — 15 minutes. We review your report and tell you exactly what can be removed before you spend anything.",
    "h1": "Hard Inquiry Removal — Book Your Free 15-Minute Consultation",
    "lede": "Answer six quick questions. We'll match you to the right plan, confirm your inquiries qualify for removal, and get your free consultation scheduled — all before you spend a single dollar. 🔒 Free. No obligation. No credit card required. Takes under 3 minutes.",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Get My Free Credit Analysis",
    "secondaryCta": "See How It Works",
    "secondaryHref": "/how-it-works"
  },
  "/experian-hard-inquiry-removal": {
    "route": "/experian-hard-inquiry-removal",
    "name": "Experian Hard Inquiry Removal",
    "title": "Experian Hard Inquiry Removal | Since 2015 | Inquiry Removal",
    "description": "Dispute and remove unauthorized hard inquiries from your Experian credit report using federal law. Free consultation. Flat fee. 100% money-back guarantee.",
    "h1": "Experian Hard Inquiry Removal — Using Federal Law, Not Guesswork",
    "lede": "If there are hard inquiries on your Experian report that you didn't authorize — from a dealership that sent your application everywhere, a lender who pulled your credit without permission, or someone who used your identity — you have the legal right to dispute them. We build the custom dispute letters, handle every communication with Experian, and fight for every removal your situation qualifies for. - ✅ 100,437 Hard Inquiries Removed  |  ⭐ 4.9 Stars — 312 Google Reviews  |  🔒 100% Money-Back Guarantee",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Get My Free Experian Analysis",
    "secondaryCta": "See How It Works →",
    "secondaryHref": "/how-it-works"
  },
  "/equifax-hard-inquiry-removal": {
    "route": "/equifax-hard-inquiry-removal",
    "name": "Equifax Hard Inquiry Removal",
    "title": "Equifax Hard Inquiry Removal | Since 2015 | Inquiry Removal",
    "description": "Dispute unauthorized Equifax hard inquiries with custom letters, federal law, and CFPB escalation when needed. Free consultation. Flat fee.",
    "h1": "Equifax Hard Inquiry Removal — Even If Equifax Already Said No",
    "lede": "Equifax has a documented history of improperly denying legitimate dispute requests — the Consumer Financial Protection Bureau fined them $15 million in 2025 for exactly that. If there are unauthorized hard inquiries on your Equifax report, or if Equifax has already verified or denied a dispute you believe should have been removed, you have legal options that go far beyond what Equifax's dispute center offers. - ✅ 100,437 Hard Inquiries Removed  |  ⭐ 4.9 Stars — 312 Google Reviews  |  🔒 100% Money-Back Guarantee",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Get My Free Equifax Analysis",
    "secondaryCta": "See How It Works →",
    "secondaryHref": "/how-it-works"
  },
  "/transunion-hard-inquiry-removal": {
    "route": "/transunion-hard-inquiry-removal",
    "name": "TransUnion Hard Inquiry Removal",
    "title": "TransUnion Hard Inquiry Removal | Since 2015 | Inquiry Removal",
    "description": "Dispute unauthorized TransUnion hard inquiries — including ones found on Credit Karma. Custom disputes. Free consultation. Flat fee. 100% guarantee.",
    "h1": "TransUnion Hard Inquiry Removal — Including Credit Karma Inquiries",
    "lede": "Tens of millions of people check their credit through Credit Karma — which pulls directly from TransUnion. If you spotted a hard inquiry on Credit Karma that you didn't authorize, couldn't dispute successfully through Credit Karma's Direct Dispute tool, or simply don't recognize — that inquiry is on your TransUnion report and it has a legal path to removal. We handle every step using federal law, custom disputes, and direct submission to TransUnion. - ✅ 100,437 Hard Inquiries Removed  |  ⭐ 4.9 Stars — 312 Google Reviews  |  🔒 100% Money-Back Guarantee",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Get My Free TransUnion Analysis",
    "secondaryCta": "See How It Works →",
    "secondaryHref": "/how-it-works"
  },
  "/car-dealership-inquiry-removal": {
    "route": "/car-dealership-inquiry-removal",
    "name": "Car Dealership Inquiry Removal",
    "title": "Car Dealership Hard Inquiry Removal | FCRA | Inquiry Removal",
    "description": "Car dealership ran your credit without permission? We remove unauthorized dealer hard inquiries from all 3 bureaus. Free consult. Flat fee. Guaranteed.",
    "h1": "Car Dealership Inquiry Removal — Remove Every Unauthorized Pull",
    "lede": "Car dealerships run credit without authorization more than any other business in America. They promise soft pulls. They submit applications to lenders you never approved. They run your credit for test drives, trade-in quotes, and financing conversations you never agreed to. Every one of those unauthorized pulls left a hard inquiry on your Experian, Equifax, and TransUnion reports — and every unauthorized inquiry has a legal path to removal. - ✅ 100,437 Hard Inquiries Removed  |  ⭐ 4.9 Stars — 312 Google Reviews  |  🔒 100% Money-Back Guarantee",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Get My Free Dealer Inquiry Analysis",
    "secondaryCta": "See How It Works →",
    "secondaryHref": "/how-it-works"
  },
  "/los-angeles-hard-inquiry-removal": {
    "route": "/los-angeles-hard-inquiry-removal",
    "name": "Los Angeles Hard Inquiry Removal",
    "title": "Hard Inquiry Removal Los Angeles | CA Law | Inquiry Removal",
    "description": "Remove unauthorized hard inquiries in Los Angeles. California law gives you extra rights. Free consultation. Flat fee. 100% money-back guarantee.",
    "h1": "Hard Inquiry Removal Los Angeles — More Rights Under California Law",
    "lede": "If you have unauthorized hard inquiries on your Experian, Equifax, or TransUnion credit report — from a car dealership that ran your credit without permission, a lender who pulled your report without authorization, or an identity theft incident — California residents have legal protections under both federal and state law to challenge and remove them. We handle the entire process from anywhere in Los Angeles, all three bureaus, one flat fee.",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Get My Free Los Angeles Credit Analysis",
    "secondaryCta": "See How It Works →",
    "secondaryHref": "/how-it-works"
  },
  "/phoenix-hard-inquiry-removal": {
    "route": "/phoenix-hard-inquiry-removal",
    "name": "Phoenix Hard Inquiry Removal",
    "title": "Hard Inquiry Removal Phoenix | Founded 2015 | Inquiry Removal",
    "description": "Phoenix-based hard inquiry removal specialist — founded after Valley dealerships hit our founder's credit. Free consultation. Flat fee. 100% guarantee.",
    "h1": "Hard Inquiry Removal Phoenix — Founded Here in 2015 by Robert Garcia",
    "lede": "Robert Garcia started Inquiry Removal in Phoenix in 2015 after Valley car dealerships sent his credit application to lenders he never authorized — dropping his score over 100 points overnight. He had worked inside the financial industry for years. He knew the law. And he knew that what those dealerships had done to him was happening to thousands of Phoenix-area residents who had no idea they had any legal recourse. So he built the only company in the country that does nothing but remove hard inquiries — right here in the 602. - ✅ 100,437 Hard Inquiries Removed Nationwide  |  ⭐ 4.9 Stars — 312 Google Reviews  |  🔒 100% Money-Back Guarantee  |  📍 Phoenix-Based Since 2015",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Get My Free Phoenix Credit Analysis",
    "secondaryCta": "Call Robert Directly — 602-377-6626",
    "secondaryHref": "tel:+16023776626"
  },
  "/new-york-city-hard-inquiry-removal": {
    "route": "/new-york-city-hard-inquiry-removal",
    "name": "New York City Hard Inquiry Removal",
    "title": "Hard Inquiry Removal NYC | NY Law Rights | Inquiry Removal",
    "description": "Remove unauthorized hard inquiries in NYC — apartments, dealerships, employers, identity theft. New York law adds extra rights. Free consultation.",
    "h1": "Hard Inquiry Removal NYC — Apartments, Dealers, Employers, ID Theft",
    "lede": "New York City is unlike any other market in the country when it comes to unauthorized hard inquiries. Landlords run credit checks on every apartment application. Car dealerships in Queens and Long Island shotgun applications to lenders. Employers sometimes pull credit without proper authorization. And New York State has its own credit reporting law — on top of federal FCRA protections — that gives NYC residents additional legal rights most people never find out about. We handle all of it. All five boroughs, the Tri-State area, all three bureaus, one flat fee.",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Get My Free NYC Credit Analysis",
    "secondaryCta": "Call Us Directly — 602-377-6626",
    "secondaryHref": "tel:+16023776626"
  },
  "/privacy-policy": {
    "route": "/privacy-policy",
    "name": "Privacy Policy",
    "title": "Privacy Policy | Inquiry Removal",
    "description": "Learn how Inquiry Removal collects, uses, and protects your personal and credit information. Plain-language privacy policy for all clients nationwide.",
    "h1": "Privacy Policy — Inquiry Removal",
    "lede": "",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Get My Free Credit Analysis",
    "secondaryCta": "See How It Works",
    "secondaryHref": "/how-it-works"
  },
  "/hard-inquiry-removal-mortgage": {
    "route": "/hard-inquiry-removal-mortgage",
    "name": "Hard Inquiry Removal for Mortgage Approval",
    "title": "Hard Inquiry Removal Mortgage | Flat Fee | Inquiry Removal",
    "description": "Hard inquiries blocking your mortgage? We remove unauthorized pulls from all 3 bureaus. Free consultation. Flat fee. 100% money-back guarantee.",
    "h1": "Hard Inquiry Removal for Mortgage Approval — Before Your Closing Date",
    "lede": "Ninety percent of the clients who come to Inquiry Removal share one goal: homeownership. Most of them were told by their lender that their credit score is the problem — and that the inquiries dragging it down came from a car dealership visit, a round of rate shopping, or a period of applying for credit that happened before they understood what it would cost them. Those inquiries have a legal path to removal. And we work with the urgency that a closing date demands. - ✅ 100,437 Hard Inquiries Removed  |  ⭐ 4.9 Stars — 312 Google Reviews  |  🔒 100% Money-Back Guarantee  |  ⚡ Disputes Submitted Within 24 Hours",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Get My Free Mortgage Credit Analysis",
    "secondaryCta": "Call Us Now — 602-377-6626",
    "secondaryHref": "tel:+16023776626"
  },
  "/unauthorized-hard-inquiry-removal": {
    "route": "/unauthorized-hard-inquiry-removal",
    "name": "Unauthorized Hard Inquiry Removal",
    "title": "Unauthorized Hard Inquiry Removal | FCRA | Inquiry Removal",
    "description": "Company pulled your credit without permission? FCRA violation. We dispute and remove unauthorized hard inquiries from all 3 bureaus. Free consultation.",
    "h1": "Unauthorized Hard Inquiry Removal — Federal Law Is on Your Side",
    "lede": "The Fair Credit Reporting Act does not allow any company to access your credit report as a hard inquiry without a legally recognized permissible purpose. If you found a hard inquiry on your Experian, Equifax, or TransUnion report from a company you never authorized — a dealership that sent your application to lenders without your approval, a creditor who pulled your report without your knowledge, or a company you've never heard of at all — that pull violated federal law. You have the right to dispute it. We know exactly how. - ✅ 100,437 Hard Inquiries Removed  |  ⭐ 4.9 Stars — 312 Google Reviews  |  🔒 100% Money-Back Guarantee  |  ⚖️ FCRA — Your Federal Right",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Get My Free Unauthorized Inquiry Analysis",
    "secondaryCta": "Call Us Now — 602-377-6626",
    "secondaryHref": "tel:+16023776626"
  },
  "/identity-theft-inquiry-removal": {
    "route": "/identity-theft-inquiry-removal",
    "name": "Identity Theft Inquiry Removal",
    "title": "Hard Inquiry Removal — Identity Theft | Inquiry Removal",
    "description": "Someone used your identity to open credit. We remove every fraudulent hard inquiry from all 3 bureaus using your FTC report. Free consultation.",
    "h1": "Identity Theft Hard Inquiry Removal — Every Fraudulent Pull Removed",
    "lede": "Identity theft leaves hard inquiries across your Experian, Equifax, and TransUnion credit reports from accounts you never opened, with companies you never contacted, in cities you've never visited. None of those inquiries had any permissible purpose under federal law — because you did not authorize a single one of them. The FTC identity theft report you can file today, combined with the legal dispute process we build for you, creates the strongest case for inquiry removal available anywhere in credit law. We handle all of it — all three bureaus, every fraudulent pull, one flat fee. - ✅ 100,437 Hard Inquiries Removed  |  ⭐ 4.9 Stars — 312 Google Reviews  |  🔒 100% Money-Back Guarantee  |  ⚖️ Strongest Legal Case We Handle",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Get My Free Identity Theft Credit Analysis",
    "secondaryCta": "Call Us Now — 602-377-6626",
    "secondaryHref": "tel:+16023776626"
  },
  "/thank-you": {
    "route": "/thank-you",
    "name": "Thank You / Confirmation Page",
    "title": "Consultation Request Received | Inquiry Removal",
    "description": "Your request has been received. Review next steps, save our contact information, and learn what to prepare for your Inquiry Removal consultation.",
    "h1": "Your Consultation Request Has Been Received",
    "lede": "Thank you for reaching out to Inquiry Removal. Your request has been submitted successfully. A team member reviews your request and contacts you using the information you provided. Keep access to your credit reports and any inquiry details available for your consultation.",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Return to Home",
    "secondaryCta": "Review How It Works",
    "secondaryHref": "/how-it-works"
  },
  "/faq": {
    "route": "/faq",
    "name": "FAQ Page — Inquiry Removal",
    "title": "Hard Inquiry Removal FAQs | Inquiry Removal",
    "description": "Answers to common questions about hard inquiries, credit bureaus, dealership pulls, identity theft, mortgage preparation, pricing, and the dispute process.",
    "h1": "Frequently Asked Questions About Hard Inquiry Removal",
    "lede": "Answers to common questions about hard inquiries, credit bureaus, dealership inquiries, identity theft, and the dispute process.",
    "ogImage": "/images/og/inquiry-removal-default-og.webp",
    "primaryCta": "Get My Free Credit Analysis",
    "secondaryCta": "See How It Works",
    "secondaryHref": "/how-it-works"
  }
};
